DROP SCHEMA public CASCADE;
CREATE SCHEMA IF NOT EXISTS user_service AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS subscriptions_service AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS notifications_service AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS security AUTHORIZATION postgres;