server:
  port: ${SERVER_PORT:8002}

spring:
  page:
    size: ${PAGE_SIZE:10}
  config:
    activate:
      on-profile: default
  application:
    name:  notifications_service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URI:http://localhost:8080/realms/subOne}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/subOne?currentSchema=notifications_service}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    properties:
      enable.idempotence: true
      request.timeout.ms: 15000
      delivery.timeout.ms: 20000
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: notification-service
      properties:
        spring:
          json:
            trusted:
              packages: "*"
