/* tslint:disable */
/* eslint-disable */
/**
 * SubscriptionsService API
 * Документация API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration.ts';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common.ts';
import type { RequestArgs } from './base.ts';
// @ts-ignore
import { BASE_PATH, BaseAPI, operationServerMap } from './base.ts';

export interface RequestSubscriptionDto {
    'serviceName': string;
    'subscriptionName': string;
    'startDate': string;
    'endDate': string;
    'paymentPeriod': RequestSubscriptionDtoPaymentPeriodEnum;
    'amount': number;
}

export const RequestSubscriptionDtoPaymentPeriodEnum = {
    Monthly: 'MONTHLY',
    Yearly: 'YEARLY'
} as const;

export type RequestSubscriptionDtoPaymentPeriodEnum = typeof RequestSubscriptionDtoPaymentPeriodEnum[keyof typeof RequestSubscriptionDtoPaymentPeriodEnum];

export interface RequestUpdateSubscriptionDto {
    'serviceName'?: string;
    'subscriptionName'?: string;
    'amount'?: number;
    'statusStop'?: boolean;
}
export interface ResponseAnalyticPaymentSubscriptionDto {
    'datePaid'?: string;
    'amount'?: number;
}
export interface ResponseAnalyticPaymentSubscriptionsDto {
    'paymentsInfo'?: Array<ResponseAnalyticPaymentSubscriptionDto>;
}
export interface ResponseSubscriptionDto {
    'id'?: number;
    'serviceName'?: string;
    'subscriptionName'?: string;
    'startDate'?: string;
    'endDate'?: string;
    'paymentPeriod'?: string;
    'amount'?: number;
    'status'?: string;
    'updatedAt'?: string;
}
export interface ResponseSubscriptionsDto {
    'subscriptions'?: Array<ResponseSubscriptionDto>;
}
export interface ResponseTotalAnalyticGroupsDto {
    'count'?: number;
    'totalSum'?: number;
}
export interface ResponseTotalAnalyticSubscriptionDto {
    'alreadyPaid'?: number;
    'lastDatePaid'?: string;
}
export interface ResponseTotalAnalyticSubscriptionGroupDto {
    'totalAmount'?: number;
    'approxMonthPaid'?: number;
    'approxYearPaid'?: number;
}

/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Удаление подписки для определенной группы
         * @param {number} groupId 
         * @param {number} subscriptionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSubscription: async (groupId: number, subscriptionId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupId' is not null or undefined
            assertParamExists('deleteSubscription', 'groupId', groupId)
            // verify required parameter 'subscriptionId' is not null or undefined
            assertParamExists('deleteSubscription', 'subscriptionId', subscriptionId)
            const localVarPath = `/api/v1/groups/{groupId}/subscriptions/{subscriptionId}`
                .replace(`{${"groupId"}}`, encodeURIComponent(String(groupId)))
                .replace(`{${"subscriptionId"}}`, encodeURIComponent(String(subscriptionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Продления подписки по числу (число = значение из PaymentPeriod)
         * @param {number} groupId 
         * @param {number} subscriptionId 
         * @param {number} extensionCount 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        extendSubscription: async (groupId: number, subscriptionId: number, extensionCount: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupId' is not null or undefined
            assertParamExists('extendSubscription', 'groupId', groupId)
            // verify required parameter 'subscriptionId' is not null or undefined
            assertParamExists('extendSubscription', 'subscriptionId', subscriptionId)
            // verify required parameter 'extensionCount' is not null or undefined
            assertParamExists('extendSubscription', 'extensionCount', extensionCount)
            const localVarPath = `/api/v1/groups/{groupId}/subscriptions/{subscriptionId}/extend/{extensionCount}`
                .replace(`{${"groupId"}}`, encodeURIComponent(String(groupId)))
                .replace(`{${"subscriptionId"}}`, encodeURIComponent(String(subscriptionId)))
                .replace(`{${"extensionCount"}}`, encodeURIComponent(String(extensionCount)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Получение аналитических данных группы (контрольная сумма, примерная -> оплата в месяц, оплата в год)
         * @param {number} groupId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAlreadyPaidGroup: async (groupId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupId' is not null or undefined
            assertParamExists('getAlreadyPaidGroup', 'groupId', groupId)
            const localVarPath = `/api/v1/groups/{groupId}/subscriptions/analytic/group-summary`
                .replace(`{${"groupId"}}`, encodeURIComponent(String(groupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Получение аналитических данных подписки
         * @param {number} groupId 
         * @param {number} subscriptionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAnalyticSubscriptionById: async (groupId: number, subscriptionId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupId' is not null or undefined
            assertParamExists('getAnalyticSubscriptionById', 'groupId', groupId)
            // verify required parameter 'subscriptionId' is not null or undefined
            assertParamExists('getAnalyticSubscriptionById', 'subscriptionId', subscriptionId)
            const localVarPath = `/api/v1/groups/{groupId}/subscriptions/{subscriptionId}/analytic`
                .replace(`{${"groupId"}}`, encodeURIComponent(String(groupId)))
                .replace(`{${"subscriptionId"}}`, encodeURIComponent(String(subscriptionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Получение данных оплаты
         * @param {number} groupId 
         * @param {number} subscriptionId 
         * @param {number} page 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPaymentInfoSubscriptionById: async (groupId: number, subscriptionId: number, page: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupId' is not null or undefined
            assertParamExists('getPaymentInfoSubscriptionById', 'groupId', groupId)
            // verify required parameter 'subscriptionId' is not null or undefined
            assertParamExists('getPaymentInfoSubscriptionById', 'subscriptionId', subscriptionId)
            // verify required parameter 'page' is not null or undefined
            assertParamExists('getPaymentInfoSubscriptionById', 'page', page)
            const localVarPath = `/api/v1/groups/{groupId}/subscriptions/{subscriptionId}/payment-info`
                .replace(`{${"groupId"}}`, encodeURIComponent(String(groupId)))
                .replace(`{${"subscriptionId"}}`, encodeURIComponent(String(subscriptionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", [], configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Получение подписки по id для определенной группы
         * @param {number} groupId 
         * @param {number} subscriptionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSubscriptionById: async (groupId: number, subscriptionId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupId' is not null or undefined
            assertParamExists('getSubscriptionById', 'groupId', groupId)
            // verify required parameter 'subscriptionId' is not null or undefined
            assertParamExists('getSubscriptionById', 'subscriptionId', subscriptionId)
            const localVarPath = `/api/v1/groups/{groupId}/subscriptions/{subscriptionId}`
                .replace(`{${"groupId"}}`, encodeURIComponent(String(groupId)))
                .replace(`{${"subscriptionId"}}`, encodeURIComponent(String(subscriptionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Получение всех подписок для определенной группы
         * @param {number} groupId 
         * @param {number} page 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSubscriptionsGroup: async (groupId: number, page: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupId' is not null or undefined
            assertParamExists('getSubscriptionsGroup', 'groupId', groupId)
            // verify required parameter 'page' is not null or undefined
            assertParamExists('getSubscriptionsGroup', 'page', page)
            const localVarPath = `/api/v1/groups/{groupId}/subscriptions`
                .replace(`{${"groupId"}}`, encodeURIComponent(String(groupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", [], configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Получение аналитики всех групп пользователя (общая оплата, количество подписок)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTotalAnalyticGroups: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/groups/me/analytic`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Создание подписки для определенной группы
         * @param {number} groupId 
         * @param {RequestSubscriptionDto} requestSubscriptionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveSubscription: async (groupId: number, requestSubscriptionDto: RequestSubscriptionDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupId' is not null or undefined
            assertParamExists('saveSubscription', 'groupId', groupId)
            // verify required parameter 'requestSubscriptionDto' is not null or undefined
            assertParamExists('saveSubscription', 'requestSubscriptionDto', requestSubscriptionDto)
            const localVarPath = `/api/v1/groups/{groupId}/subscriptions`
                .replace(`{${"groupId"}}`, encodeURIComponent(String(groupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", [], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(requestSubscriptionDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Изменение подписки для определенной группы
         * @param {number} groupId 
         * @param {number} subscriptionId 
         * @param {RequestUpdateSubscriptionDto} requestUpdateSubscriptionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSubscription: async (groupId: number, subscriptionId: number, requestUpdateSubscriptionDto: RequestUpdateSubscriptionDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupId' is not null or undefined
            assertParamExists('updateSubscription', 'groupId', groupId)
            // verify required parameter 'subscriptionId' is not null or undefined
            assertParamExists('updateSubscription', 'subscriptionId', subscriptionId)
            // verify required parameter 'requestUpdateSubscriptionDto' is not null or undefined
            assertParamExists('updateSubscription', 'requestUpdateSubscriptionDto', requestUpdateSubscriptionDto)
            const localVarPath = `/api/v1/groups/{groupId}/subscriptions/{subscriptionId}`
                .replace(`{${"groupId"}}`, encodeURIComponent(String(groupId)))
                .replace(`{${"subscriptionId"}}`, encodeURIComponent(String(subscriptionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", [], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(requestUpdateSubscriptionDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Удаление подписки для определенной группы
         * @param {number} groupId 
         * @param {number} subscriptionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteSubscription(groupId: number, subscriptionId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteSubscription(groupId, subscriptionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deleteSubscription']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Продления подписки по числу (число = значение из PaymentPeriod)
         * @param {number} groupId 
         * @param {number} subscriptionId 
         * @param {number} extensionCount 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async extendSubscription(groupId: number, subscriptionId: number, extensionCount: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.extendSubscription(groupId, subscriptionId, extensionCount, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.extendSubscription']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Получение аналитических данных группы (контрольная сумма, примерная -> оплата в месяц, оплата в год)
         * @param {number} groupId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAlreadyPaidGroup(groupId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseTotalAnalyticSubscriptionGroupDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAlreadyPaidGroup(groupId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getAlreadyPaidGroup']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Получение аналитических данных подписки
         * @param {number} groupId 
         * @param {number} subscriptionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAnalyticSubscriptionById(groupId: number, subscriptionId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseTotalAnalyticSubscriptionDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAnalyticSubscriptionById(groupId, subscriptionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getAnalyticSubscriptionById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Получение данных оплаты
         * @param {number} groupId 
         * @param {number} subscriptionId 
         * @param {number} page 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPaymentInfoSubscriptionById(groupId: number, subscriptionId: number, page: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseAnalyticPaymentSubscriptionsDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPaymentInfoSubscriptionById(groupId, subscriptionId, page, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getPaymentInfoSubscriptionById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Получение подписки по id для определенной группы
         * @param {number} groupId 
         * @param {number} subscriptionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSubscriptionById(groupId: number, subscriptionId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseSubscriptionsDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSubscriptionById(groupId, subscriptionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getSubscriptionById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Получение всех подписок для определенной группы
         * @param {number} groupId 
         * @param {number} page 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSubscriptionsGroup(groupId: number, page: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseSubscriptionsDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSubscriptionsGroup(groupId, page, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getSubscriptionsGroup']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Получение аналитики всех групп пользователя (общая оплата, количество подписок)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTotalAnalyticGroups(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseTotalAnalyticGroupsDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTotalAnalyticGroups(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getTotalAnalyticGroups']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Создание подписки для определенной группы
         * @param {number} groupId 
         * @param {RequestSubscriptionDto} requestSubscriptionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async saveSubscription(groupId: number, requestSubscriptionDto: RequestSubscriptionDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseSubscriptionDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.saveSubscription(groupId, requestSubscriptionDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.saveSubscription']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Изменение подписки для определенной группы
         * @param {number} groupId 
         * @param {number} subscriptionId 
         * @param {RequestUpdateSubscriptionDto} requestUpdateSubscriptionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateSubscription(groupId: number, subscriptionId: number, requestUpdateSubscriptionDto: RequestUpdateSubscriptionDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateSubscription(groupId, subscriptionId, requestUpdateSubscriptionDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.updateSubscription']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Удаление подписки для определенной группы
         * @param {number} groupId 
         * @param {number} subscriptionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSubscription(groupId: number, subscriptionId: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteSubscription(groupId, subscriptionId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Продления подписки по числу (число = значение из PaymentPeriod)
         * @param {number} groupId 
         * @param {number} subscriptionId 
         * @param {number} extensionCount 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        extendSubscription(groupId: number, subscriptionId: number, extensionCount: number, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.extendSubscription(groupId, subscriptionId, extensionCount, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Получение аналитических данных группы (контрольная сумма, примерная -> оплата в месяц, оплата в год)
         * @param {number} groupId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAlreadyPaidGroup(groupId: number, options?: RawAxiosRequestConfig): AxiosPromise<ResponseTotalAnalyticSubscriptionGroupDto> {
            return localVarFp.getAlreadyPaidGroup(groupId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Получение аналитических данных подписки
         * @param {number} groupId 
         * @param {number} subscriptionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAnalyticSubscriptionById(groupId: number, subscriptionId: number, options?: RawAxiosRequestConfig): AxiosPromise<ResponseTotalAnalyticSubscriptionDto> {
            return localVarFp.getAnalyticSubscriptionById(groupId, subscriptionId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Получение данных оплаты
         * @param {number} groupId 
         * @param {number} subscriptionId 
         * @param {number} page 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPaymentInfoSubscriptionById(groupId: number, subscriptionId: number, page: number, options?: RawAxiosRequestConfig): AxiosPromise<ResponseAnalyticPaymentSubscriptionsDto> {
            return localVarFp.getPaymentInfoSubscriptionById(groupId, subscriptionId, page, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Получение подписки по id для определенной группы
         * @param {number} groupId 
         * @param {number} subscriptionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSubscriptionById(groupId: number, subscriptionId: number, options?: RawAxiosRequestConfig): AxiosPromise<ResponseSubscriptionsDto> {
            return localVarFp.getSubscriptionById(groupId, subscriptionId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Получение всех подписок для определенной группы
         * @param {number} groupId 
         * @param {number} page 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSubscriptionsGroup(groupId: number, page: number, options?: RawAxiosRequestConfig): AxiosPromise<ResponseSubscriptionsDto> {
            return localVarFp.getSubscriptionsGroup(groupId, page, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Получение аналитики всех групп пользователя (общая оплата, количество подписок)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTotalAnalyticGroups(options?: RawAxiosRequestConfig): AxiosPromise<ResponseTotalAnalyticGroupsDto> {
            return localVarFp.getTotalAnalyticGroups(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Создание подписки для определенной группы
         * @param {number} groupId 
         * @param {RequestSubscriptionDto} requestSubscriptionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveSubscription(groupId: number, requestSubscriptionDto: RequestSubscriptionDto, options?: RawAxiosRequestConfig): AxiosPromise<ResponseSubscriptionDto> {
            return localVarFp.saveSubscription(groupId, requestSubscriptionDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Изменение подписки для определенной группы
         * @param {number} groupId 
         * @param {number} subscriptionId 
         * @param {RequestUpdateSubscriptionDto} requestUpdateSubscriptionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSubscription(groupId: number, subscriptionId: number, requestUpdateSubscriptionDto: RequestUpdateSubscriptionDto, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.updateSubscription(groupId, subscriptionId, requestUpdateSubscriptionDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Удаление подписки для определенной группы
     * @param {number} groupId 
     * @param {number} subscriptionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteSubscription(groupId: number, subscriptionId: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deleteSubscription(groupId, subscriptionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Продления подписки по числу (число = значение из PaymentPeriod)
     * @param {number} groupId 
     * @param {number} subscriptionId 
     * @param {number} extensionCount 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public extendSubscription(groupId: number, subscriptionId: number, extensionCount: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).extendSubscription(groupId, subscriptionId, extensionCount, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Получение аналитических данных группы (контрольная сумма, примерная -> оплата в месяц, оплата в год)
     * @param {number} groupId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAlreadyPaidGroup(groupId: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getAlreadyPaidGroup(groupId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Получение аналитических данных подписки
     * @param {number} groupId 
     * @param {number} subscriptionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAnalyticSubscriptionById(groupId: number, subscriptionId: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getAnalyticSubscriptionById(groupId, subscriptionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Получение данных оплаты
     * @param {number} groupId 
     * @param {number} subscriptionId 
     * @param {number} page 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getPaymentInfoSubscriptionById(groupId: number, subscriptionId: number, page: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getPaymentInfoSubscriptionById(groupId, subscriptionId, page, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Получение подписки по id для определенной группы
     * @param {number} groupId 
     * @param {number} subscriptionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getSubscriptionById(groupId: number, subscriptionId: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getSubscriptionById(groupId, subscriptionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Получение всех подписок для определенной группы
     * @param {number} groupId 
     * @param {number} page 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getSubscriptionsGroup(groupId: number, page: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getSubscriptionsGroup(groupId, page, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Получение аналитики всех групп пользователя (общая оплата, количество подписок)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getTotalAnalyticGroups(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getTotalAnalyticGroups(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Создание подписки для определенной группы
     * @param {number} groupId 
     * @param {RequestSubscriptionDto} requestSubscriptionDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public saveSubscription(groupId: number, requestSubscriptionDto: RequestSubscriptionDto, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).saveSubscription(groupId, requestSubscriptionDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Изменение подписки для определенной группы
     * @param {number} groupId 
     * @param {number} subscriptionId 
     * @param {RequestUpdateSubscriptionDto} requestUpdateSubscriptionDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateSubscription(groupId: number, subscriptionId: number, requestUpdateSubscriptionDto: RequestUpdateSubscriptionDto, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).updateSubscription(groupId, subscriptionId, requestUpdateSubscriptionDto, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * DevSchedulerControllerApi - axios parameter creator
 */
export const DevSchedulerControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generateSubscriptionsAnalytic: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/scheduler/dev/generate/analytic`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendMessageWithAlreadyPaymentInfo: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/scheduler/dev/send/message/payment/already`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendMessageWithPaymentInfo: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/scheduler/dev/send/message/payment`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateStatusSubscriptions: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/scheduler/dev/update/status/subscription`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DevSchedulerControllerApi - functional programming interface
 */
export const DevSchedulerControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DevSchedulerControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async generateSubscriptionsAnalytic(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: string; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.generateSubscriptionsAnalytic(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DevSchedulerControllerApi.generateSubscriptionsAnalytic']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sendMessageWithAlreadyPaymentInfo(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: string; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sendMessageWithAlreadyPaymentInfo(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DevSchedulerControllerApi.sendMessageWithAlreadyPaymentInfo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sendMessageWithPaymentInfo(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: string; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sendMessageWithPaymentInfo(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DevSchedulerControllerApi.sendMessageWithPaymentInfo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateStatusSubscriptions(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: string; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateStatusSubscriptions(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DevSchedulerControllerApi.updateStatusSubscriptions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DevSchedulerControllerApi - factory interface
 */
export const DevSchedulerControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DevSchedulerControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generateSubscriptionsAnalytic(options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: string; }> {
            return localVarFp.generateSubscriptionsAnalytic(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendMessageWithAlreadyPaymentInfo(options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: string; }> {
            return localVarFp.sendMessageWithAlreadyPaymentInfo(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendMessageWithPaymentInfo(options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: string; }> {
            return localVarFp.sendMessageWithPaymentInfo(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateStatusSubscriptions(options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: string; }> {
            return localVarFp.updateStatusSubscriptions(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DevSchedulerControllerApi - object-oriented interface
 */
export class DevSchedulerControllerApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public generateSubscriptionsAnalytic(options?: RawAxiosRequestConfig) {
        return DevSchedulerControllerApiFp(this.configuration).generateSubscriptionsAnalytic(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public sendMessageWithAlreadyPaymentInfo(options?: RawAxiosRequestConfig) {
        return DevSchedulerControllerApiFp(this.configuration).sendMessageWithAlreadyPaymentInfo(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public sendMessageWithPaymentInfo(options?: RawAxiosRequestConfig) {
        return DevSchedulerControllerApiFp(this.configuration).sendMessageWithPaymentInfo(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateStatusSubscriptions(options?: RawAxiosRequestConfig) {
        return DevSchedulerControllerApiFp(this.configuration).updateStatusSubscriptions(options).then((request) => request(this.axios, this.basePath));
    }
}



