server:
  port: ${SERVER_PORT:8000}
spring:
  page:
    size: ${PAGE_SIZE:10}
  config:
    activate:
      on-profile: dev
  application:
    name: user_service
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URI:http://localhost:8080/realms/subOne}
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/subOne}
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
    default-schema: user_service
    enabled: true
  r2dbc:
    url: ${SPRING_DATASOURCE_URL_REACTIVE:r2dbc:postgresql://localhost:5432/subOne?schema=user_service}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
    pool:
      initial-size: 2
      max-size: 10
      max-idle-time: 30m
      max-life-time: 2h
      validation-query: SELECT 1
      validation-depth: remote
      leak-detection-threshold: 3000
    properties:
      connectTimeout: 5s
      socketTimeout: 30s
  kafka:
    partitions_keycloak_consumer: 3
    topicNameDeleteUser: ${KAFKA_NAME_TOPIC_DELETE_USER:delete_user}
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    group-id: user-service
    properties:
      enable.idempotence: true
      request.timeout.ms: 15000
      delivery.timeout.ms: 20000
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: user-service
      properties:
        spring:
          json:
            trusted:
              packages: "com.subOne.kecyloak_dto"
management:
  endpoints:
    web:
      exposure:
        include: health, beans
  endpoint:
    health:
      show-details: always
logging:
  level:
    root: INFO
    org.springframework.web.reactive.function.client: DEBUG
    org.springframework.r2dbc.connection: DEBUG
    org.springframework.data.r2dbc.core: DEBUG
    io.r2dbc.spi: DEBUG