/* tslint:disable */
/* eslint-disable */
/**
 * NotificationsService API
 * Документация API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration.ts';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common.ts';
import type { RequestArgs } from './base.ts';
// @ts-ignore
import { BASE_PATH, BaseAPI, operationServerMap } from './base.ts';

export interface RequestUpdateNotificationsDto {
    'ids': Array<number>;
}
export interface ResponseNotificationDto {
    'id'?: number;
    'notificationTargetType'?: ResponseNotificationDtoNotificationTargetTypeEnum;
    'notificationType'?: ResponseNotificationDtoNotificationTypeEnum;
    'targetId'?: number;
    'createdAt'?: string;
}

export const ResponseNotificationDtoNotificationTargetTypeEnum = {
    Group: 'GROUP',
    Subscription: 'SUBSCRIPTION'
} as const;

export type ResponseNotificationDtoNotificationTargetTypeEnum = typeof ResponseNotificationDtoNotificationTargetTypeEnum[keyof typeof ResponseNotificationDtoNotificationTargetTypeEnum];
export const ResponseNotificationDtoNotificationTypeEnum = {
    DeleteMember: 'DELETE_MEMBER',
    AddMember: 'ADD_MEMBER',
    ChangeOwner: 'CHANGE_OWNER',
    CreateUser: 'CREATE_USER',
    PayemntSubscription: 'PAYEMNT_SUBSCRIPTION',
    AlreadyPayemntSubs: 'ALREADY_PAYEMNT_SUBS'
} as const;

export type ResponseNotificationDtoNotificationTypeEnum = typeof ResponseNotificationDtoNotificationTypeEnum[keyof typeof ResponseNotificationDtoNotificationTypeEnum];

export interface ResponseNotificationsCountDto {
    'count'?: number;
}
export interface ResponseNotificationsDto {
    'notifications'?: Array<ResponseNotificationDto>;
}

/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Получение количество не прочитанных уведомлений пользователя
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCountNotificationsNew: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/notifications/count`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Получение непрочитанных уведомлений пользователя
         * @param {number} page 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNewNotifications: async (page: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'page' is not null or undefined
            assertParamExists('getNewNotifications', 'page', page)
            const localVarPath = `/api/v1/notifications/new`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", [], configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Получение прочитанных уведомлений пользователя
         * @param {number} page 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOldNotifications: async (page: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'page' is not null or undefined
            assertParamExists('getOldNotifications', 'page', page)
            const localVarPath = `/api/v1/notifications/old`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", [], configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Обновление уведомлений (прочитать)
         * @param {RequestUpdateNotificationsDto} requestUpdateNotificationsDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateNotifications: async (requestUpdateNotificationsDto: RequestUpdateNotificationsDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'requestUpdateNotificationsDto' is not null or undefined
            assertParamExists('updateNotifications', 'requestUpdateNotificationsDto', requestUpdateNotificationsDto)
            const localVarPath = `/api/v1/notifications`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", [], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(requestUpdateNotificationsDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Получение количество не прочитанных уведомлений пользователя
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCountNotificationsNew(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseNotificationsCountDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCountNotificationsNew(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getCountNotificationsNew']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Получение непрочитанных уведомлений пользователя
         * @param {number} page 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getNewNotifications(page: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseNotificationsDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getNewNotifications(page, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getNewNotifications']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Получение прочитанных уведомлений пользователя
         * @param {number} page 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getOldNotifications(page: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseNotificationsDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getOldNotifications(page, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getOldNotifications']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Обновление уведомлений (прочитать)
         * @param {RequestUpdateNotificationsDto} requestUpdateNotificationsDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateNotifications(requestUpdateNotificationsDto: RequestUpdateNotificationsDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: string; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateNotifications(requestUpdateNotificationsDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.updateNotifications']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Получение количество не прочитанных уведомлений пользователя
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCountNotificationsNew(options?: RawAxiosRequestConfig): AxiosPromise<ResponseNotificationsCountDto> {
            return localVarFp.getCountNotificationsNew(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Получение непрочитанных уведомлений пользователя
         * @param {number} page 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNewNotifications(page: number, options?: RawAxiosRequestConfig): AxiosPromise<ResponseNotificationsDto> {
            return localVarFp.getNewNotifications(page, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Получение прочитанных уведомлений пользователя
         * @param {number} page 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOldNotifications(page: number, options?: RawAxiosRequestConfig): AxiosPromise<ResponseNotificationsDto> {
            return localVarFp.getOldNotifications(page, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Обновление уведомлений (прочитать)
         * @param {RequestUpdateNotificationsDto} requestUpdateNotificationsDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateNotifications(requestUpdateNotificationsDto: RequestUpdateNotificationsDto, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: string; }> {
            return localVarFp.updateNotifications(requestUpdateNotificationsDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Получение количество не прочитанных уведомлений пользователя
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCountNotificationsNew(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getCountNotificationsNew(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Получение непрочитанных уведомлений пользователя
     * @param {number} page 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getNewNotifications(page: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getNewNotifications(page, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Получение прочитанных уведомлений пользователя
     * @param {number} page 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getOldNotifications(page: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getOldNotifications(page, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Обновление уведомлений (прочитать)
     * @param {RequestUpdateNotificationsDto} requestUpdateNotificationsDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateNotifications(requestUpdateNotificationsDto: RequestUpdateNotificationsDto, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).updateNotifications(requestUpdateNotificationsDto, options).then((request) => request(this.axios, this.basePath));
    }
}



